### ISSUE TITLE
[TODO] More metadata

### ISSUE THREAD

**Issue by ObserverOfTime** [evangelos-ch/MangAdventure#5]
- [ ] Serialize models into JSON-LD
- [ ] Use [comics-manifest](https://github.com/HadrienGardeur/comics-manifest) for series
- [ ] Heroku Procfile & [app.json](https://devcenter.heroku.com/articles/app-json-schema)
- [ ] [Web App Manifest](https://developers.google.com/web/fundamentals/web-app-manifest/)
- [ ] [Sitemap](https://docs.djangoproject.com/en/2.1/ref/contrib/sitemaps/)
